### ISSUE TITLE
Valid arrays are throwing error

### ISSUE THREAD

**Issue by federico-reina-melt** [MeltStudio/config-loader#2]
## Describe the problem
Valid arrays aren't properly type checked, throwing errors even when the settings object matches the loaded configuration
## Steps to reproduce:
Create a Settings object with the following structure:
```typescript
const settings = new Settings(
    {
      features: option.array({
        required: true,
        item: option.object({
          required: true,
          item: {
            name: option.string(),
            enabled: option.bool(),
          },
        }),
      }),
    },
    {
      env: false,
      args: true,
      files: path.join(__dirname, "./config.yaml"),
    }
  );
```
Create a config.yaml file with the following contents:
```yaml
socialMedia: [https://twitter.com/example, https://instagram.com/example, 1]
features:
  - name: Store
    enabled: true
  - name: Admin
    enabled: false
```

## Expected result
Code should run without errors.
## Actual result:
```
[Error]: Required option 'features.0' not provided.      
[Error]: Required option 'features.1' not provided.
```
