### ISSUE TITLE
Enhance type inference for returned value of Settings.get()

### ISSUE THREAD

**Issue by federico-reina-melt** [MeltStudio/config-loader#32]
## Describe the problem
When giving a structure to the Settings object, it should ensure type inference for the generated configuration object
## Steps to reproduce:
Create a Settings object with the following structure:
```typescript
const settings = new Settings(
    {
      socialMedia: option.array({
        required: true,
        item: option.string({ required: true }),
      }),
      features: option.array({
        required: true,
        item: {
          name: option.string(),
          enabled: option.bool(),
        },
      }),
    },
    {
      env: false,
      args: true,
      files: path.join(__dirname, "./config.yaml"),
    }
  );
```
Create a config.yaml file with the following contents:
```yaml
socialMedia: [https://twitter.com/example, https://instagram.com/example, 1]
features:
  - name: Store
    enabled: true
  - name: Admin
    enabled: false
```
 
## Expected result
After calling settings.get(), the result should have a correct inferenced type, in this case:
```typescript
{
  socialMedia: string[],
  features: {
    name: string,
    enabled: boolean
  }[]
}
```
## Actual result:
settings.get() only has a type if a generic is given to the Settings constructor (`new Settings<SomeClass>()`) else it will be typed as `any`
